### ISSUE TITLE
Score Logique (Multiply with chain good answer)

### ISSUE THREAD

**Issue by Midunighto** [WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Red-Force#20]
Score Good Answers : 100pts (if 4 answers)
Score Good Answers : 50pts (if 2 answers)

Hard : x3 if 3 bonne réponses d'affilé
Moyen : x2 if 3 bonne réponses d'affilé
Easy :  None

**Comment by Batsave** [comment]
DONE ✅🚀
